### PR TITLE
Export metrics on ECS service deployment status

### PR DESCRIPTION
**Pull request by peterbuecker-form3**
This PR makes metrics on ECS service deployments available. This is helpful to understand how deployments of services are progressing, and also to diagnose if they got stuck.

To enable this change, and to bring in some security improvements, all Go dependencies have been updated to the latest versions as well. Go itself is updated to version 1.19.

With this change, for an ECS cluster `my-cluster` with a service `my-service`, you'll get the following metrics. Notice how multiple deployments can be present at the same time:

```
ecs_deployment_rollout_state{cluster="my-cluster",deployment="ecs-svc/4517230642530929340",region="eu-west-1",rollout_state="COMPLETED",service="my-svc"} 1
ecs_deployment_rollout_state{cluster="my-cluster",deployment="ecs-svc/4517230642530929340",region="eu-west-1",rollout_state="FAILED",service="my-svc"} 0
ecs_deployment_rollout_state{cluster="my-cluster",deployment="ecs-svc/4517230642530929340",region="eu-west-1",rollout_state="IN_PROGRESS",service="my-svc"} 0
ecs_deployment_rollout_state{cluster="my-cluster",deployment="ecs-svc/6689178114241617301",region="eu-west-1",rollout_state="COMPLETED",service="my-svc"} 0
ecs_deployment_rollout_state{cluster="my-cluster",deployment="ecs-svc/6689178114241617301",region="eu-west-1",rollout_state="FAILED",service="my-svc"} 0
ecs_deployment_rollout_state{cluster="my-cluster",deployment="ecs-svc/6689178114241617301",region="eu-west-1",rollout_state="IN_PROGRESS",service="my-svc"} 1
ecs_deployment_desired_tasks{cluster="my-cluster",deployment="ecs-svc/4517230642530929340",region="eu-west-1",service="my-svc"} 3
ecs_deployment_desired_tasks{cluster="my-cluster",deployment="ecs-svc/6689178114241617301",region="eu-west-1",service="my-svc"} 0
ecs_deployment_pending_tasks{cluster="my-cluster",deployment="ecs-svc/4517230642530929340",region="eu-west-1",service="my-svc"} 0
ecs_deployment_pending_tasks{cluster="my-cluster",deployment="ecs-svc/6689178114241617301",region="eu-west-1",service="my-svc"} 0
ecs_deployment_running_tasks{cluster="my-cluster",deployment="ecs-svc/4517230642530929340",region="eu-west-1",service="my-svc"} 2
ecs_deployment_running_tasks{cluster="my-cluster",deployment="ecs-svc/6689178114241617301",region="eu-west-1",service="my-svc"} 0
ecs_deployment_failed_tasks{cluster="my-cluster",deployment="ecs-svc/4517230642530929340",region="eu-west-1",service="my-svc"} 0
ecs_deployment_failed_tasks{cluster="my-cluster",deployment="ecs-svc/6689178114241617301",region="eu-west-1",service="my-svc"} 0
```

### CODE REVIEW

**Comment by andrew-bulford-form3** [comment]
Running `go mod vendor` locally removes the `vendor/github.com/Sirupsen/logrus` directory for me - looks like it's been replaced by the lower-case version?

**Comment by peterbuecker-form3** [comment]
@andrew-bulford-form3 on which local Go version are you? I ran `go mod vendor` & `go mod tidy` on Go 1.19.4, and there's no additional changes.

**Comment by andrew-bulford-form3** [comment]
> @andrew-bulford-form3 on which local Go version are you? I ran `go mod vendor` & `go mod tidy` on Go 1.19.4, and there's no additional changes.

Ah, that could explain it, looks like I'm on a slightly newer version:
```
> go version
go version go1.19.6 linux/amd64
```

**Comment by peterbuecker-form3** [comment]
@andrew-bulford-form3 Oh wait, it's actually something else. I'm on Mac - that's case-insensitive. Could you push the changes to the branch so it's clean?

**Comment by andrew-bulford-form3** [comment]
> @andrew-bulford-form3 Oh wait, it's actually something else. I'm on Mac - that's case-insensitive. Could you push the changes to the branch so it's clean?

Ooh OK, nice find, I expected the tooling to be more consistent than that.  Have pushed the change :+1:.

**Review by andrew-bulford-form3 — APPROVED** [review]
Looks good!  Will be really nice to get this visibility in Grafana, awesome work! :rocket:

**Pull request merged**
